spring.profiles.active=test

# Configuration for test email server
default.sender=mjgomes1978@gmail.com
default.recipient=mjgomes1978@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mjgomes1978@gmail.com
spring.mail.password=oylu iojj mnux bjmy 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=SequenciaDeCaracteresParaAssinarToken
jwt.expiration=60000
