spring.profiles.active=test

spring.jackson.use-jackson2-defaults=true

# Configuration for dev email server
default.sender=mjgomes1978@gmail.com
default.recipient=mjgomes1978@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mjgomes1978@gmail.com
spring.mail.password=oylu iojj mnux bjmy 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=SequenciaDeCaracteresParaAssinarToken
jwt.expiration=86400000

# AWS S3 Configuration
aws.access_key_id=
aws.secret_access_key=
s3.bucket=dev-ionic
s3.region=sa-east-1

# Images Configuration
img.prefix.client.profile=cp
img.profile.size=200

# Upload Images Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
